blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogCreateView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('', BlogListView.as_view(), name='article_list'),
    path('article/<int:pk>/', BlogDetailView.as_view(), name='article'),
    path('create/', BlogCreateView.as_view(), name='create'),
    path('article/<slug:slug>/', BlogDetailView.as_view(), name='article_slug'),
    path('update/<int:pk>/', BlogUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),

]

catalog/urls.py
from django.urls import path

from catalog.apps import CatalogConfig
from catalog.views import get_contacts, ProductListView, ProductDetailView

app_name = CatalogConfig.name


urlpatterns = [
    path('', ProductListView.as_view(), name='product_list'),
    path('contacts/', get_contacts, name='contacts'),
    path('product_details/<int:pk>/', ProductDetailView.as_view(), name='product')

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


NULLABLE = {"null": True, "blank": True}


class Blog(models.Model):
    title = models.CharField(max_length=100, verbose_name="Заголовок")
    slug = models.CharField(max_length=100, verbose_name="Slug", **NULLABLE)
    content = models.TextField(verbose_name="Содержимое")
    preview = models.ImageField(upload_to="blogs/", verbose_name="Превью", **NULLABLE)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    is_published = models.BooleanField(default=True, verbose_name="Опубликовано")
    views_count = models.IntegerField(default=0, verbose_name="Кол-во просмотров")

    class Meta:
        verbose_name = "статья"
        verbose_name_plural = "статьи"
        ordering = ["-pk"]

    def __str__(self):
        return self.title

catalog/models.py
from django.db import models

NULLABLE = {"null": True, "blank": True}


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name="Наименование")
    description = models.TextField(verbose_name="Описание")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "категория"
        verbose_name_plural = "категории"
        ordering = ['pk']


class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name="Наименование")
    description = models.TextField(verbose_name="Описание")
    image = models.ImageField(upload_to="product_images/", verbose_name="Превью продукта", **NULLABLE)
    category_id = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name="Категория")
    price = models.IntegerField(default=0, verbose_name="Цена")
    created_at = models.DateTimeField(verbose_name="Дата создания")
    last_change = models.DateTimeField(verbose_name="Дата изменения")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "продукт"
        verbose_name_plural = "продукты"
        ordering = ['pk']

blog/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView, DetailView, DeleteView
from pytils.translit import slugify
from django.urls import reverse

from blog.models import Blog


# Create your views here.
class BlogListView(ListView):
    model = Blog
    paginate_by = 3

    extra_context = {
        'title': 'Личный блок - MyBlog',
        'section_name': 'Каталог статей',
    }

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class BlogCreateView(CreateView):
    model = Blog
    fields = ('title', 'slug', 'preview', 'content', 'is_published',)
    success_url = reverse_lazy('blog:article_list')

    def form_valid(self, form):
        if form.is_valid():
            new_article = form.save()
            new_article.slug = slugify(new_article.title)
            new_article.save()

        return super().form_valid(form)


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ('title', 'slug', 'preview', 'content', 'is_published',)
    # success_url = reverse_lazy('blog:article_list')

    def form_valid(self, form):
        if form.is_valid():
            new_article = form.save()
            new_article.slug = slugify(new_article.title)
            new_article.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:article', args=[self.kwargs.get('pk')])


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:article_list')

catalog/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.core.paginator import Paginator
from django.views.generic import ListView, DetailView

from catalog.models import Product


class ProductListView(ListView):
    model = Product
    paginate_by = 4

    extra_context = {
        'title': 'Каталог товаров - MyStore',
        'section_name': 'Каталог',
    }


class ProductDetailView(DetailView):
    model = Product

    extra_context = {
        'section_name': 'Информация о продукте',
    }


def get_contacts(request):
    context = {
        'title': 'Контакты',
        'section_name': 'Контакты',
    }
    if request.method == 'POST':
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        print(f'Новое сообщение от {name}({phone}): {message}')
    return render(request, 'catalog/contacts.html', context)

blog/templates/blog/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">MyBlog</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="{% url 'blog:article_list' %}">Статьи</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:product_list' %}">Каталог товаров</a>
    </nav>
</div>

<div class="pricing-header px-3 py-3 pt-md-1 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{ section_name }}</h1>
</div>

<div class="container">

    {% block content %}

    {% endblock %}

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; {% now 'Y' %}</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

</body>
</html>

blog/templates/blog/blog_confirm_delete.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-12">
            <div class="card box-shadow mr-4">
                <div class="card-header mb-3"><h3>Удаление статьи</h3></div>
                <form method="post" class="mx-3">
                    {% csrf_token %}
                    <p>Уверены, что хотите удалить статью "{{ object.title }}"?</p>
                    <button type="submit" class="btn btn-danger mb-3">Да, удалить</button>
                    <a class="btn btn-success mb-3" href="{% url 'blog:article_list' %}">Нет</a>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'blog/base.html' %}
{% block content %}

    {% load path_tags %}
    <div class="row text-start">
        <div class="col-lg-12 col-md-6 col-sm-12">
            <div class="card box-shadow">
                <div class="card-body">
                    <div class="card-header"><h1 class="text-center">{{ object.title }} ({{ object.slug }})</h1></div>
                    <table class="table table-striped">
                        <img src="{% mediapath object.preview %}" class="mx-auto mb-3 mt-3 d-block img-thumbnail"
                             alt="Image"/>
                        <tr>
                            <p class="mt-3 text-justify">{{ object.content }}</p>
                        </tr>
                        <tr>
                            <td class="w-25">Статья создана</td>
                            <td>{{ object.created_at }}</td>
                        </tr>
                        <tr>
                            <td class="w-25">Количество просмотров</td>
                            <td>{{ object.views_count }}</td>
                        </tr>
                    </table>
                    <a href="{% url 'blog:article_list' %}" class="btn btn-outline-dark">Назад </a>
                </div>

            </div>

        </div>

    </div>

{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-12">
            <div class="card box-shadow mr-4">
                <div class="card-header mb-3"><h3>Создание статьи</h3></div>
                <form method="post" class="mx-3" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success mb-3">
                        {% if object %}
                        Изменить статью
                        {% else %}
                        Создать статью
                        {% endif %}
                    </button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'blog/base.html' %}
{% block content %}
    {% load blog_tags %}
    <div class="col-12 mb-3">
        <a class="btn btn-outline-dark" href="{% url 'blog:create' %}">Добавить статью</a>
    </div>
    <div class="row text-center">
        {% for article in object_list %}
            <div class="col-12">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-2 font-weight-normal text-center">
                            {{ article.title|truncatechars:250 }}</h4>
                        <img src="{% mediapath article.preview %}" class="mx-auto d-block img-thumbnail" alt="Image"/>

                    </div>
                    <div class="card-body">
                        <h1 class="card-title pricing-card-title">{{ article.created_date }}</h1>
                        <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                            <li>{{ article.content|truncatechars:500 }}</li>
                        </ul>
                        <div class="d-block align-items-center">
                            <div class="btn-group" role="group" aria-label="Basic outlined example">
                                <a href="{% url 'blog:article' article.pk %}">
                                    <button class="btn btn-outline-dark" type="button">Подробнее</button>
                                </a>
                                <a href="{% url 'blog:update' article.pk %}">
                                    <button class="btn btn-outline-dark" type="button">Изменить</button>
                                </a>
                                <a href="{% url 'blog:delete' article.pk %}">
                                    <button class="btn btn-outline-danger" type="button">Удалить</button>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    {% include 'catalog/includes/inc_pagination.html' %}

{% endblock %}

catalog/templates/catalog/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">MyStore</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:product_list' %}">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:contacts' %}">Контакты</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'blog:article_list' %}">Блог</a>
    </nav>
</div>

<div class="pricing-header px-3 py-3 pt-md-1 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{ section_name }}</h1>
</div>

<div class="container">

    {% block content %}

    {% endblock %}

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; {% now 'Y' %}</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

</body>
</html>

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}
{% block content %}

    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя"
                                   required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone"
                                   placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message"
                                      placeholder="Введите ваше сообщение" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>

                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/includes/inc_pagination.html
<nav aria-label="navig">
    <ul class="nav justify-content-center">
        {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="?page=1">1</a></li>
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1">Previous</a>
            </li>

        {% endif %}

        <li class="page-item active">
            <span class="page-link">
                {{ page_obj.number }}
                <span class="sr-only">(current)</span>
            </span>
        </li>

        {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>

            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
            </li>
        {% endif %}

    </ul>
<br /><p style="text-align: center">Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}</p>
</nav>

catalog/templates/catalog/includes/inc_product_detail.html
{% load path_tags %}
<div class="row text-start">
    <div class="col-lg-12 col-md-6 col-sm-12">
        <div class="card mb-4 box-shadow">
            <div class="card-body">
                <div class="card-header"><h1>{{ object.name }}</h1></div>
                <table class="table table-striped">
                    <img src="{% mediapath object.image %}" width="300" height="300" class="mx-auto d-block img-thumbnail" alt="Image" />
                    <tr>
                        <td class="w-25">Описание</td>
                        <td>{{ object.description|truncatechars:100 }}</td>
                    </tr>
                    <tr>
                        <td class="w-25">Цена</td>
                        <td>$ {{ object.price }}</td>
                    </tr>
                    <tr>
                        <td class="w-25">Категория товара</td>
                        <td>{{ object.category_id }}</td>
                    </tr>
                </table>
                <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>

            </div>
        </div>
    </div>

</div>

catalog/templates/catalog/includes/inc_product_details.html
{% load path_tags %}
<div class="row text-start">
    <div class="col-lg-12 col-md-6 col-sm-12">
        <div class="card mb-4 box-shadow">
            <div class="card-body">
                <div class="card-header"><h1>{{ product_info.name }}</h1></div>
                <table class="table table-striped">
                    <img src="{% mediapath product_info.image %}" width="300" height="300" class="mx-auto d-block img-thumbnail" alt="Image" />
                    <tr>
                        <td class="w-25">Описание</td>
                        <td>{{ product_info.description|truncatechars:100 }}</td>
                    </tr>
                    <tr>
                        <td class="w-25">Цена</td>
                        <td>$ {{ product_info.price }}</td>
                    </tr>
                    <tr>
                        <td class="w-25">Категория товара</td>
                        <td>{{ product_info.category_id }}</td>
                    </tr>
                </table>
                <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>

            </div>
        </div>
    </div>

</div>

catalog/templates/catalog/index.html
{% extends 'catalog/base.html' %}
{% block content %}

    <div class="row text-center">
        {% for product in page_obj %}
            <div class="col-6">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">{{ product }}</h4>
                    </div>
                    <div class="card-body">
                        <h1 class="card-title pricing-card-title">$ {{ product.price }}</h1>
                        <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                            <li>- {{ product.description }}</li>
                        </ul>
                        <a href="/product_details/{{ product.pk }}/">
                            <button class="btn btn-outline-dark" type="button">Подробнее</button>
                        </a>

                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    {% include 'catalog/includes/inc_pagination.html' %}
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% block content %}

    {% include 'catalog/includes/inc_product_detail.html' %}

{% endblock %}

catalog/templates/catalog/product_details.html
{% extends 'catalog/base.html' %}
{% block content %}

    {% include 'catalog/includes/inc_product_details.html' %}

{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% block content %}

    <div class="row text-center">
        {% for product in object_list %}
            <div class="col-6">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">{{ product }}</h4>
                    </div>
                    <div class="card-body">
                        <h1 class="card-title pricing-card-title">$ {{ product.price }}</h1>
                        <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                            <li>- {{ product.description }}</li>
                        </ul>
                        <a href="/product_details/{{ product.pk }}/">
                            <button class="btn btn-outline-dark" type="button">Подробнее</button>
                        </a>

                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    {% include 'catalog/includes/inc_pagination.html' %}
{% endblock %}